apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-http
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.service.http.svc_annotations | indent 4 }}
spec:
  type: {{ .Values.service.http.serviceType }}
  {{- if (.Values.service.http.loadBalancerIP) and eq .Values.service.http.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.http.loadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    {{- if  .Values.service.http.nodePort }}
    nodePort: {{ .Values.service.http.nodePort }}
    {{- end }}
    targetPort: {{ .Values.service.http.port }}
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
