name: Helm Gitea CI
on:
  push:
    branches: ["develop", "master", "feature/**"]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      # https://github.com/engineerd/setup-kind
      - uses: engineerd/setup-kind@v0.4.0
        with:
          skipClusterCreation: true

      - name: Create the Kind Cluster for test
        run: |
          go run mage.go -v kind:recreate

      - name: Create the Kind Cluster for test
        run: |
          make build

      - name: remove the kind cluster
        if: ${{ always() }}
        run: |
          kind delete cluster
